name: LobbyTools
main: de.lucawimmer.lobbytools.LobbyTools
version: 1.4
authors:
 - magl1te
description: Some tool for a perfect lobby
commands:
  lobbytools:
    aliases: [lt, lobbytool]
    description: Main command for LobbyTools
    usage: /lobbytools <reload/toggle>